
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CharacterInfo : Luban.BeanBase
{
    public CharacterInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["comment"].IsString) { throw new SerializationException(); }  Comment = _buf["comment"]; }
        { if(!_buf["health"].IsNumber) { throw new SerializationException(); }  Health = _buf["health"]; }
        { if(!_buf["stamina"].IsNumber) { throw new SerializationException(); }  Stamina = _buf["stamina"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
    }

    public static CharacterInfo DeserializeCharacterInfo(JSONNode _buf)
    {
        return new CharacterInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 初始生命值
    /// </summary>
    public readonly float Health;
    /// <summary>
    /// 耐力值
    /// </summary>
    public readonly float Stamina;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 基础移动速度
    /// </summary>
    public readonly float Speed;
   
    public const int __ID__ = -991295657;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "comment:" + Comment + ","
        + "health:" + Health + ","
        + "stamina:" + Stamina + ","
        + "attack:" + Attack + ","
        + "speed:" + Speed + ","
        + "}";
    }
}
}

