
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EnemyInfo : Luban.BeanBase
{
    public EnemyInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["comment"].IsString) { throw new SerializationException(); }  Comment = _buf["comment"]; }
        { if(!_buf["health"].IsNumber) { throw new SerializationException(); }  Health = _buf["health"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["ignore_terrain"].IsBoolean) { throw new SerializationException(); }  IgnoreTerrain = _buf["ignore_terrain"]; }
    }

    public static EnemyInfo DeserializeEnemyInfo(JSONNode _buf)
    {
        return new EnemyInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Health;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 基础移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 无视地形
    /// </summary>
    public readonly bool IgnoreTerrain;
   
    public const int __ID__ = 953467958;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "comment:" + Comment + ","
        + "health:" + Health + ","
        + "attack:" + Attack + ","
        + "speed:" + Speed + ","
        + "ignoreTerrain:" + IgnoreTerrain + ","
        + "}";
    }
}
}

