
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TBChracterInfo TBChracterInfo {get; }
    public TBEnemyInfo TBEnemyInfo {get; }
    public TBWeaponInfo TBWeaponInfo {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TBChracterInfo = new TBChracterInfo(loader("tbchracterinfo"));
        TBEnemyInfo = new TBEnemyInfo(loader("tbenemyinfo"));
        TBWeaponInfo = new TBWeaponInfo(loader("tbweaponinfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TBChracterInfo.ResolveRef(this);
        TBEnemyInfo.ResolveRef(this);
        TBWeaponInfo.ResolveRef(this);
    }
}

}
