
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBEnemyInfo
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyInfo> _dataMap;
    private readonly System.Collections.Generic.List<EnemyInfo> _dataList;
    
    public TBEnemyInfo(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyInfo>();
        _dataList = new System.Collections.Generic.List<EnemyInfo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EnemyInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.EnemyInfo.DeserializeEnemyInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EnemyInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyInfo> DataList => _dataList;

    public EnemyInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyInfo Get(int key) => _dataMap[key];
    public EnemyInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

