
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBWeaponInfo
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponInfo> _dataMap;
    private readonly System.Collections.Generic.List<WeaponInfo> _dataList;
    
    public TBWeaponInfo(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponInfo>();
        _dataList = new System.Collections.Generic.List<WeaponInfo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeaponInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.WeaponInfo.DeserializeWeaponInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponInfo> DataList => _dataList;

    public WeaponInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponInfo Get(int key) => _dataMap[key];
    public WeaponInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

