
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WeaponInfo : Luban.BeanBase
{
    public WeaponInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["comment"].IsString) { throw new SerializationException(); }  Comment = _buf["comment"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["bullet_speed"].IsNumber) { throw new SerializationException(); }  BulletSpeed = _buf["bullet_speed"]; }
        { if(!_buf["ignore_terrain"].IsNumber) { throw new SerializationException(); }  IgnoreTerrain = _buf["ignore_terrain"]; }
        { if(!_buf["piercing"].IsNumber) { throw new SerializationException(); }  Piercing = _buf["piercing"]; }
    }

    public static WeaponInfo DeserializeWeaponInfo(JSONNode _buf)
    {
        return new WeaponInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 子弹移动速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 子弹消失时间
    /// </summary>
    public readonly float IgnoreTerrain;
    /// <summary>
    /// 穿透敌人数量
    /// </summary>
    public readonly int Piercing;
   
    public const int __ID__ = -929298166;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "comment:" + Comment + ","
        + "attack:" + Attack + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "ignoreTerrain:" + IgnoreTerrain + ","
        + "piercing:" + Piercing + ","
        + "}";
    }
}
}

