
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemInfo : Luban.BeanBase
{
    public ItemInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["comment"].IsString) { throw new SerializationException(); }  Comment = _buf["comment"]; }
        { if(!_buf["type"].IsString) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["kind"].IsString) { throw new SerializationException(); }  Kind = _buf["kind"]; }
        { if(!_buf["rarity"].IsString) { throw new SerializationException(); }  Rarity = _buf["rarity"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["parameter"].IsString) { throw new SerializationException(); }  Parameter = _buf["parameter"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static ItemInfo DeserializeItemInfo(JSONNode _buf)
    {
        return new ItemInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 种类
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// 二级分类
    /// </summary>
    public readonly string Kind;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly string Rarity;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly string Parameter;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = 1241839233;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "comment:" + Comment + ","
        + "type:" + Type + ","
        + "kind:" + Kind + ","
        + "rarity:" + Rarity + ","
        + "description:" + Description + ","
        + "parameter:" + Parameter + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

