
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBChracterInfo
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterInfo> _dataMap;
    private readonly System.Collections.Generic.List<CharacterInfo> _dataList;
    
    public TBChracterInfo(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterInfo>();
        _dataList = new System.Collections.Generic.List<CharacterInfo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.CharacterInfo.DeserializeCharacterInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterInfo> DataList => _dataList;

    public CharacterInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterInfo Get(int key) => _dataMap[key];
    public CharacterInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

