
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBItemInfo
{
    private readonly System.Collections.Generic.Dictionary<int, ItemInfo> _dataMap;
    private readonly System.Collections.Generic.List<ItemInfo> _dataList;
    
    public TBItemInfo(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemInfo>();
        _dataList = new System.Collections.Generic.List<ItemInfo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ItemInfo.DeserializeItemInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemInfo> DataList => _dataList;

    public ItemInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemInfo Get(int key) => _dataMap[key];
    public ItemInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

